import {test,after,before} from 'node:test';
import assert from 'node:assert/strict';
import {createApp} from '../server.mjs';
let server,base;
before(async()=>{delete process.env.DEEPSEEK_API_KEY;server=createApp();await new Promise(r=>server.listen(0,'127.0.0.1',r));base=`http://127.0.0.1:${server.address().port}`;});
after(()=>new Promise(r=>server.close(r)));
test('config exposes only the lab URL',async()=>{const p=await(await fetch(base+'/api/config')).json();assert.deepEqual(Object.keys(p),['labUrl']);assert.match(p.labUrl,/^https:\/\/wl.nobook.com/);});
test('invalid stage and malformed JSON return 400 without crashing',async()=>{for(const body of ['{','{"stage":4,"text":"test"}','{"stage":7,"text":"test"}','{"stage":1,"text":""}']){const r=await fetch(base+'/api/chat',{method:'POST',body});assert.equal(r.status,400);}assert.equal((await fetch(base+'/')).status,200);});
test('offline feedback is explicitly a self-check, not a diagnosis',async()=>{const p=await(await fetch(base+'/api/chat',{method:'POST',body:JSON.stringify({stage:2,text:'我们预测像会变大'})})).json();assert.equal(p.source,'fallback');assert.match(p.content,/暂时无法提供针对性反馈/);});
test('static source files outside public cannot be read',async()=>{for(const p of ['/server.mjs','/%2e%2e%2fserver.mjs']){const r=await fetch(base+p);assert.notEqual(r.status,200);}});
